intial setup stuff!
googleinterns/step137-2020 pull request #1
Opened 2020-06-25 22:16 UTC by lexidelorey

adding maven and appengine stuff so we can run dev servers and ultimately deploy

2020-06-26 16:28 UTC, usaeedw requested changes

2020-06-26 16:28 UTC, usaeed-w commented on pom.xml
> +</project>
Add a new line at the end of all these files. 

I recommend setting up your editor so that it does this automatically for you.

2020-06-26 19:24 UTC, ellisvivian submitted a review, later dismissed

2020-06-29 16:28 UTC, usaeedw approved these changes

2020-06-29 16:28 UTC, merged